import type { Metadata } from "next";
import { motion } from "framer-motion";

import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "@/components/providers";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster />
          <div className="flex flex-col min-h-screen">
            {/* <Header /> */}
            <main className="flex-grow">{children}</main>
            {/* <FashionCursor /> */}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
