import type { Metadata } from "next";

import { Inter } from "next/font/google";

import Footer2 from "./_components/footer2";
import Header from "./_components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      {/* <Header /> */}
      <div className="flex-grow">{children}</div>
      <Footer2 />
    </div>
  );
}
